[fix] Add --purge
YunoHost-Apps/pleroma_ynh pull request #192
Opened 2022-02-24 21:11 UTC by Galettofraise

## Problem

- *To add option --purge*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-02-25 00:46 UTC, yalh76 requested changes
Thanks

I think the datadir variable is missing in the remove script

2022-02-27 20:32 UTC, zamentur approved these changes

2022-02-27 20:32 UTC, zamentur commented
!testme

2022-03-01 01:31 UTC, yalh76 commented
!testme

2022-03-10 19:44 UTC, merged